# Generated by Django 2.2.5 on 2020-03-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='adults',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='children',
            field=models.IntegerField(),
        ),
    ]
