# Generated by Django 2.2.5 on 2020-02-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('activities_id', models.AutoField(primary_key=True, serialize=False)),
                ('activities', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('difficulty_id', models.AutoField(primary_key=True, serialize=False)),
                ('difficulty', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PackageDays',
            fields=[
                ('days_id', models.AutoField(primary_key=True, serialize=False)),
                ('days', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TravelMode',
            fields=[
                ('travel_id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_mode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='Package_Images/')),
                ('difficulty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Difficulty')),
            ],
        ),
        migrations.CreateModel(
            name='PackagePlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_details', models.CharField(max_length=40)),
                ('days', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.PackageDays')),
                ('difficulty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Difficulty')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Packages')),
            ],
        ),
        migrations.CreateModel(
            name='PackageActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Activities')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Packages')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.PackagePlan')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('destination_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=30)),
                ('package_destination', models.ManyToManyField(to='home.Packages')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitiesTravelMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Activities')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Packages')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.PackagePlan')),
                ('travel_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TravelMode')),
            ],
        ),
    ]
