# Generated by Django 2.2.5 on 2020-02-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='start_price',
            field=models.IntegerField(default=150, max_length=10),
            preserve_default=False,
        ),
    ]
