# Generated by Django 2.2.5 on 2020-03-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_packages_start_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=20)),
                ('adults', models.IntegerField(max_length=20)),
                ('children', models.IntegerField(max_length=20)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('airport_pickup', models.CharField(max_length=20)),
                ('airline', models.CharField(max_length=20)),
                ('flight_number', models.CharField(max_length=20)),
                ('arrival_time', models.TimeField()),
                ('package_Category', models.CharField(max_length=20)),
                ('payment_mode', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='packages',
            name='start_price',
            field=models.IntegerField(),
        ),
    ]
